title: Kabaddi!
hero_image: images/banner.png
description: Make a game inspired by kabaddi, where the player must tag opponents and avoid being caught, while managing a countdown timer
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: Set up the Stage
    completion: engaged
  - title: Set up the player and controls
  - title: Add opponents
  - title: Tagging and being caught
    completion: internal
  - title: Make the kabaddi timer
  - title: Challenge
    challenge: true
  - title: What next?
    completion: external
