title: Kabaddi!
hero_image: images/banner.png
description: Make a tag-style game inspired by kabaddi, where the player must cross a line, tag opponents, and return safely while managing a countdown timer by pressing the spacebar to "breathe"! 
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: Stage setup
  - title: Player setup and controls
  - title: Add opponents
  - title: Tagging and being caught
  - title: Make the Kabaddi timer
  - title: Challenge!
  - title: What can you do now?
